//Dashboard
export const DASHBOARD_SET_EDIT_ROW = 'DASHBOARD_SET_EDIT_ROW';
export const DASHBOARD_CHANGE_ROW_VALUE = 'DASHBOARD_CHANGE_ROW_VALUE';
export const DASHBOARD_DISPLAY_CHANGED = 'DASHBOARD_DISPLAY_CHANGED';
export const DASHBOARD_CHANGE_PAGE = 'DASHBOARD_CHANGE_PAGE';

//Wedding Party
export const WEDDING_PARTY_ROWS_UPDATED = 'WEDDINGPARTY_ROWS_UPDATED';

//Wedding Party
export const EVENTS_ROWS_UPDATED = 'EVENTS_ROWS_UPDATED';